#############################################################################
# Makefile for building: Bazinga
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  Bazinga.pro
# Template: app
# Command: c:\lib\qt_5_3_2_vs2013\x86\bin\qmake -o Makefile Bazinga.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = c:\lib\qt_5_3_2_vs2013\x86\bin\qmake
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Bazinga.pro C:\lib\qt_5_3_2_vs2013\x86\mkspecs\win32-msvc2013\qmake.conf C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\spec_pre.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\common\shell-win32.conf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\qconfig.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axbase.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axserver.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_concurrent.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_core.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_core_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_declarative.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_declarative_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_designer.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_designer_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_enginio.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_enginio_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_gui.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_gui_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_help.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_help_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimedia.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_network.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_network_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_nfc.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_opengl.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_positioning.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_printsupport.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qml.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qml_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qmltest.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quick.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quick_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_script.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_script_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_scripttools.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sensors.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_serialport.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sql.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sql_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_svg.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_svg_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_testlib.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_uitools.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_websockets.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_widgets.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_winextras.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xml.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xml_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\qt_functions.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\qt_config.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\qt_config.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\win32-msvc2013\qmake.conf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\spec_post.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\exclusive_builds.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\default_pre.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\default_pre.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\resolve_config.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\exclusive_builds_post.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\default_post.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\c++11.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\rtti.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\precompile_header.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\warn_on.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\qt.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\resources.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\moc.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\opengl.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\uic.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\windows.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\testcase_targets.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\exceptions.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\yacc.prf \
		C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\lex.prf \
		Bazinga.pro \
		C:/lib/qt_5_3_2_vs2013/x86/lib/qtmaind.prl \
		c:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Cored.prl \
		C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Widgets.prl \
		C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Concurrent.prl \
		C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Gui.prl \
		C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Core.prl \
		C:/lib/qt_5_3_2_vs2013/x86/lib/libEGLd.prl \
		C:/lib/qt_5_3_2_vs2013/x86/lib/libGLESv2d.prl
	$(QMAKE) -o Makefile Bazinga.pro
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\spec_pre.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\common\shell-win32.conf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\qconfig.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axbase.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axbase_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axcontainer.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axserver.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_axserver_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_bluetooth.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_clucene_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_concurrent.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_core.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_core_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_declarative.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_declarative_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_designer.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_designer_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_enginio.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_enginio_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_gui.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_gui_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_help.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_help_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimedia.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_network.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_network_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_nfc.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_nfc_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_opengl.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_opengl_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_openglextensions.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_positioning.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_positioning_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_printsupport.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qml.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qml_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qmltest.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quick.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quick_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_script.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_script_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_scripttools.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sensors.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sensors_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_serialport.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_serialport_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sql.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_sql_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_svg.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_svg_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_testlib.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_testlib_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_uitools.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_uitools_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_websockets.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_websockets_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_widgets.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_widgets_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_winextras.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_winextras_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xml.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xml_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\qt_functions.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\qt_config.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\qt_config.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\win32-msvc2013\qmake.conf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\spec_post.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\exclusive_builds.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\default_pre.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\default_pre.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\resolve_config.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\exclusive_builds_post.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\default_post.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\c++11.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\rtti.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\precompile_header.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\warn_on.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\qt.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\resources.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\moc.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\opengl.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\uic.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\win32\windows.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\testcase_targets.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\exceptions.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\yacc.prf:
C:\lib\qt_5_3_2_vs2013\x86\mkspecs\features\lex.prf:
Bazinga.pro:
C:/lib/qt_5_3_2_vs2013/x86/lib/qtmaind.prl:
c:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Cored.prl:
C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Widgets.prl:
C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Concurrent.prl:
C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Gui.prl:
C:/lib/qt_5_3_2_vs2013/x86/lib/Qt5Core.prl:
C:/lib/qt_5_3_2_vs2013/x86/lib/libEGLd.prl:
C:/lib/qt_5_3_2_vs2013/x86/lib/libGLESv2d.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Bazinga.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) build_debug\Bazinga_pch.pch
	-$(DEL_FILE) ..\debug\Bazinga.exp
	-$(DEL_FILE) ..\debug\Bazinga.ilk
	-$(DEL_FILE) ..\debug\Bazinga.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) ..\debug\Bazinga.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
